[build-system]
requires = ["setuptools>=61.0", "wheel"]  # Minimum versions of required build tools
build-backend = "setuptools.build_meta"

[project]
name = "gbox"
version = "1.1.0"
description = "A convenience package for geometry related operations"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Rajesh Nakka", email = "338rajesh@gmail.com" }
]
maintainers = [
    { name = "Rajesh Nakka", email = "338rajesh@gmail.com" }
]
keywords = ["Geometry", "Shapes", "Plotting"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
requires-python = ">=3.14"
dependencies = [
    "numpy~=2.5",
    "matplotlib~=3.11",
    "scipy~=1.18",
]

[project.urls]
documentation = "https://gbox.readthedocs.io"
repository = "https://github.com/338rajesh/gbox"

[dependency-groups]
dev = [
    "ipykernel~=7.3.0",
    "numpydoc~=1.11",
    "pydata-sphinx-theme~=0.21",
    "pytest~=9.1",
    "pytest-cov~=7.1",
    "ruff~=0.16",
    "sphinx~=9.1",
    "sphinx-rtd-theme~=3.1",
]

[tool.setuptools.packages.find]
where = ["."]
