name: Publish to PyPI

# Trigger this workflow when a new tag is pushed
on:
  push:
    tags:
      - "v*.*.*"  # This pattern matches version tags like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Build the package
        run: |
          uv build

      - name: Publish package to PyPI
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv publish
